# Generated by Django 5.0.7 on 2024-07-20 16:14

import django.contrib.postgres.indexes
import enumfields.fields
import photocard.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhotoCardSale",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                ("fee", models.PositiveIntegerField(verbose_name="수수료")),
                (
                    "status",
                    enumfields.fields.EnumField(
                        default="SALE", enum=photocard.models.PhotoCardSaleStatus, max_length=20
                    ),
                ),
                ("sold_at", models.DateTimeField(null=True, verbose_name="거래 완료 일시")),
            ],
            options={
                "verbose_name": "포토 카드 판매",
                "db_table": "photo_card_sale",
            },
        ),
        migrations.CreateModel(
            name="PhotoCardSaleHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("before", models.JSONField(verbose_name="수정 전")),
                ("after", models.JSONField(verbose_name="수정 후")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "포토 카드 판매 수정 이력",
                "db_table": "photo_card_sale_history",
            },
        ),
        migrations.CreateModel(
            name="PhotoCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                (
                    "image",
                    models.ImageField(
                        upload_to=photocard.models.upload_photo_card_to, verbose_name="포토카드 대표 이미지"
                    ),
                ),
                ("artist", models.CharField(max_length=20, verbose_name="아티스트")),
                ("title", models.CharField(max_length=150, verbose_name="포토카드 명")),
                (
                    "type",
                    enumfields.fields.EnumField(
                        default="ALBUM",
                        enum=photocard.models.PhotoCardType,
                        max_length=20,
                        verbose_name="포토카드 타입",
                    ),
                ),
            ],
            options={
                "verbose_name": "포토카드",
                "db_table": "photo_card",
                "indexes": [
                    django.contrib.postgres.indexes.BrinIndex(
                        fields=["updated_at"], name="photo_card_updated_d05095_brin"
                    )
                ],
            },
        ),
    ]
