# Generated by Django 5.0.7 on 2024-07-20 16:14

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photocard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="photocardsale",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bought_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="구매자",
            ),
        ),
        migrations.AddField(
            model_name="photocardsale",
            name="photo_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="photocard.photocard", verbose_name="포토카드"
            ),
        ),
        migrations.AddField(
            model_name="photocardsale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
        migrations.AddField(
            model_name="photocardsalehistory",
            name="photo_card_sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="photocard.photocardsale", verbose_name="포토 카드 판매"
            ),
        ),
        migrations.AddIndex(
            model_name="photocardsale",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["updated_at"], name="photo_card__updated_71b5c8_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="photocardsalehistory",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["created_at"], name="photo_card__created_921a43_brin"
            ),
        ),
    ]
