# Generated by Django 5.0.7 on 2024-07-20 08:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photocard", "0002_auto_20240719_1834"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="photocard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="photocard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
        migrations.AlterField(
            model_name="photocardsale",
            name="buyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bought_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="구매자",
            ),
        ),
        migrations.AlterField(
            model_name="photocardsale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성 일시"),
        ),
        migrations.AlterField(
            model_name="photocardsale",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_sales",
                to=settings.AUTH_USER_MODEL,
                verbose_name="판매자",
            ),
        ),
        migrations.AlterField(
            model_name="photocardsale",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
        ),
        migrations.AlterField(
            model_name="photocardsalehistory",
            name="after",
            field=models.JSONField(verbose_name="수정 후"),
        ),
        migrations.AlterField(
            model_name="photocardsalehistory",
            name="before",
            field=models.JSONField(verbose_name="수정 전"),
        ),
        migrations.AddIndex(
            model_name="photocard",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["updated_at"], name="photo_card_updated_d05095_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="photocardsale",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["updated_at"], name="photo_card__updated_71b5c8_brin"
            ),
        ),
        migrations.AddIndex(
            model_name="photocardsalehistory",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["created_at"], name="photo_card__created_921a43_brin"
            ),
        ),
    ]
