# Generated by Django 5.0.7 on 2024-07-20 08:14

import enumfields.fields
import photocard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photocard", "0003_alter_photocard_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photocard",
            name="type",
            field=enumfields.fields.EnumField(
                default="ALBUM", enum=photocard.models.PhotoCardType, max_length=20, verbose_name="포토카드 타입"
            ),
        ),
        migrations.AlterField(
            model_name="photocardsale",
            name="status",
            field=enumfields.fields.EnumField(default="SALE", enum=photocard.models.PhotoCardSaleStatus, max_length=20),
        ),
    ]
