# Generated by Django 5.0.7 on 2024-07-19 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("photocard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "주문 내역",
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.PositiveIntegerField(verbose_name="판매가")),
                ("fee", models.PositiveIntegerField(verbose_name="수수료")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.order")),
                (
                    "photo_card_sale",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="photocard.photocardsale"),
                ),
            ],
            options={
                "verbose_name": "주문 아이템",
                "db_table": "order_item",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("method", models.CharField(choices=[("CASH", "현금")], max_length=25, verbose_name="결제 수단")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16, verbose_name="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기"), ("COMPLETED", "완료")], max_length=20, verbose_name="결제 상태"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "결제",
                "db_table": "payment",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.payment"),
        ),
        migrations.CreateModel(
            name="UserCash",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cash", models.IntegerField(verbose_name="사용 현금")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="order.payment"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "user_cash",
                "db_table": "user_cash",
            },
        ),
    ]
