# Generated by Django 5.0.7 on 2024-07-20 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("photocard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.order"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="photo_card_sale",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="photocard.photocardsale"),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.payment"),
        ),
        migrations.AddField(
            model_name="usercash",
            name="payment",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="order.payment"),
        ),
        migrations.AddField(
            model_name="usercash",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
