# Generated by Django 5.0.7 on 2024-07-20 08:10

import enumfields.fields
import order.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_created_at_alter_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=enumfields.fields.EnumField(
                default="현금", enum=order.models.PaymentMethod, max_length=20, verbose_name="결제 수단"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=enumfields.fields.EnumField(
                default="완료", enum=order.models.PaymentStatus, max_length=20, verbose_name="결제 상태"
            ),
        ),
    ]
